# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bitcoin-kif' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'Charts', '3.1'
  # Pods for bitcoin-kif

    target 'bitcoin-kifTests' do
        pod 'Quick', '~> 1.3.0'
        pod 'Nimble', '~> 7.1.2'
        pod 'Nimble-Snapshots'
        pod 'KIF'
        pod 'KIF-Quick'
    end

end
